// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYa2jrhUupTrOr9xO8JLhvWW2plu8hblY',
    appId: '1:124372920481:web:c31f49c9e0f9813a80a8e0',
    messagingSenderId: '124372920481',
    projectId: 'klinify-115a9',
    authDomain: 'klinify-115a9.firebaseapp.com',
    storageBucket: 'klinify-115a9.appspot.com',
    measurementId: 'G-Z2B6J94363',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRv_Oo0Y0WU8QCrsEng6VpNxoeERZDC1k',
    appId: '1:124372920481:android:2449f4f0444e83b580a8e0',
    messagingSenderId: '124372920481',
    projectId: 'klinify-115a9',
    storageBucket: 'klinify-115a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6h6yk0W_sLmhM8nXc1rfQQFqXLbGcS4',
    appId: '1:124372920481:ios:09c863551da1252580a8e0',
    messagingSenderId: '124372920481',
    projectId: 'klinify-115a9',
    storageBucket: 'klinify-115a9.appspot.com',
    iosClientId: '124372920481-k1q0aj3kjs3mcm7d1d8dd4e05eedaqm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wineandkline',
  );
}
